name: spacy
channels:
  - defaults
  - conda-forge
  - anaconda
  - pypi
  - pytorch
  - nvidia
dependencies:
  - python=3.11.6
  - pylint
  - numpy
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - torchtext
  - torchdata
  - pytorch-cuda=12.1
  - category_encoders
  - spacy
  - cupy
  - pip
  - pip:
    - ipython
    - ipywidgets
    - matplotlib
    - plotly
    - seaborn
    - seaborn-analyzer
    - scikit-learn
    - scikit-learn-intelex
    - pandas
    - jupyter
    - jupyterlab
    - opencv-python==4.8.*
    - scipy
    - pillow
    - xlrd
    - openpyxl==3.1.0
    - defusedxml
    - lxml
    - html5lib
    - beautifulsoup4
    - autopep8
    - tabulate
    - mlxtend
    - pyside6==6.5.3
