name: spacy-rapids
channels:
  - defaults
  - conda-forge
  - anaconda
  - pypi
  - nvidia
  - rapidsai
dependencies:
  - python=3.10.0
  - pylint
  - numpy
  - rapids=23.10
  - cuda-version=12.0
  - category_encoders
  - spacy
  - cupy
  - scikit-learn
  - scikit-learn-intelex
  - pip
  - pip:
    - ipython
    - ipywidgets
    - matplotlib
    - plotly
    - seaborn
    - seaborn-analyzer
    - pandas
    - jupyter
    - jupyterlab
    - opencv-python
    - scipy
    - pillow
    - xlrd
    - openpyxl==3.1.0
    - defusedxml
    - lxml
    - html5lib
    - beautifulsoup4
    - autopep8
    - tabulate
    - mlxtend
    - pyside6==6.5.3
