name: spacy
channels:
  - defaults
  - conda-forge
  - anaconda
  - pypi
  - nvidia
  - rapidsai
  - pytorch
dependencies:
  - python=3.10
  - pylint
  - numpy
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - torchtext
  - torchdata
  - rapids=23.10
  - cuda-version=12.0
  - pytorch-cuda=12.1
  - category_encoders
  - spacy
  - cupy
  - scikit-learn
  - scikit-learn-intelex
  - pip
  - pip:
    - ipython
    - ipywidgets
    - matplotlib
    - plotly
    - seaborn
    - seaborn-analyzer
    - jupyter
    - jupyterlab
    - opencv-python
    - scipy
    - pillow
    - xlrd
    - openpyxl==3.1.0
    - defusedxml
    - lxml
    - html5lib
    - beautifulsoup4
    - autopep8
    - tabulate
    - mlxtend
    - pandas==1.5.3
    - wordcloud==1.9.2
