name: pytorch-dev
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
  - pypi
dependencies:
  - python=3.11.*
  - pylint
  - ipython
  - numpy
  - pytorch=1.13.*
  - torchvision
  - torchaudio
  - torchtext
  - torchdata
# - cudatoolkit=10.2.* - Removed for MacOS
  - matplotlib
  - plotly=5.12.*
  - seaborn
  - scikit-learn
  - pandas
  - jupyter
  - opencv=4.7.*
  - scipy
  - pillow
  - xlrd
  - lxml
  - pip
  - pip:
    - jupyterlab
