name: tf
channels:
  - defaults
  - conda-forge
  - anaconda
  - pypi
  - nvidia
dependencies:
  - python=3.10.*
  - pylint
  - ipython
  - numpy
  - matplotlib
  - plotly
  - seaborn
  - scikit-learn
  - scikit-learn-intelex
  - tensorflow=2.11.*
  - pandas
  - jupyter
  - opencv
  - scipy
  - pillow
  - xlrd
  - openpyxl
  - defusedxml
  - lxml
  - html5lib
  - beautifulsoup4
  - pip
  - pip:
    - jupyterlab