name: torch
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
  - pypi
dependencies:
  - python=3.12.*
  - pylint
  - ipython
  - numpy
  - pytorch=2.4.*
  - torchvision
  - torchaudio
  - torchtext
  - torchdata
  - matplotlib
  - plotly
  - seaborn
  - scikit-learn
  - pandas
  - jupyter
  - opencv
  - scipy
  - pillow
  - xlrd
  - openpyxl
  - defusedxml
  - lxml
  - html5lib
  - beautifulsoup4
  - jupyterlab
  - pip
  - pip:
    - ipywidgets
    - seaborn-analyzer
    - pyarrow
    - autopep8
    - tabulate
    - mlxtend
    - PySide6==6.7.3
