name: torch
channels:
  - defaults
  - conda-forge
  - anaconda
  - pypi
  - pytorch
  - nvidia
dependencies:
  - python=3.12.7
  - pylint
  - numpy
  - pytorch=2.5.*
  - torchvision=0.20.*
  - torchaudio
  - torchtext
  - torchdata
  - pytorch-cuda=12.4.*
  - category_encoders
  - pip
  - pip:
    - ipython
    - ipywidgets
    - matplotlib
    - plotly
    - seaborn
    - seaborn-analyzer
    - scikit-learn
    - scikit-learn-intelex
    - pandas
    - jupyter
    - jupyterlab
    - opencv-python==4.10.*
    - scipy
    - pillow
    - xlrd
    - openpyxl==3.1.5
    - defusedxml
    - lxml
    - html5lib
    - beautifulsoup4
    - autopep8
    - tabulate
    - mlxtend
