name: spark
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
  - pypi
dependencies:
  - python=3.10.*
  - pylint
  - ipython
  - numpy
  - matplotlib
  - plotly
  - seaborn
  - scikit-learn
  - scikit-learn-intelex
  - pandas
  - jupyter
  - opencv
  - scipy
  - pillow
  - xlrd
  - openpyxl
  - defusedxml
  - lxml
  - html5lib
  - beautifulsoup4
  - jupyterlab
  - pip
  - pip:
    - pyspark==3.4.0