name: base-dev
channels:
  - defaults
  - conda-forge
  - anaconda
  - pypi
dependencies:
  - python=3.10.*
  - pylint
  - ipython
  - ipywidgets
  - numpy
  - matplotlib
  - plotly
  - seaborn
  - seaborn-analyzer
  - scikit-learn
  - scikit-learn-intelex
  - pandas
  - jupyter
  - scipy
  - pillow
  - xlrd
  - lxml
  - html5lib
  - beautifulsoup4
  - jupyterlab
  - pip
  - pip:
    - opencv-python==4.7.*
