name: tf
channels:
  - defaults
  - conda-forge
  - anaconda
  - pypi
  - nvidia
dependencies:
  - python=3.10.*
  - pylint
  - numpy
  - tensorflow=2.11.*
  - cudatoolkit=11.2.*
  - cudnn=8.1.*
  - pip
  - pip:
    - ipython
    - ipywidgets
    - matplotlib
    - plotly
    - seaborn
    - seaborn-analyzer
    - scikit-learn
    - scikit-learn-intelex
    - pandas
    - jupyter
    - jupyterlab
    - opencv-python==4.7.*
    - scipy
    - pillow
    - xlrd
    - openpyxl
    - lxml
    - html5lib
    - beautifulsoup4
  