name: base-dev
channels:
  - defaults
  - conda-forge
  - anaconda
  - pypi
dependencies:
  - python=3.10.*
  - pylint
  - ipython
  - numpy
  - matplotlib
  - plotly
  - seaborn
  - scikit-learn
  - scikit-learn-intelex
  - pandas
  - jupyter
  - opencv
  - scipy
  - pillow
  - xlrd
  - lxml
  - html5lib
  - beautifulsoup4
  - jupyterlab
