name: torch
channels:
  - defaults
  - conda-forge
  - anaconda
  - pypi
  - pytorch
  - nvidia
dependencies:
  - python=3.11.8
  - pylint
  - numpy
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchaudio
  - torchtext
  - torchdata
  - cuda-version=12.3
  - pytorch-cuda=12.1
  - category_encoders
  - pip
  - pip:
    - ipython
    - ipywidgets
    - matplotlib
    - plotly
    - seaborn
    - seaborn-analyzer
    - pandas
    - jupyter
    - jupyterlab
    - opencv-python==4.9.0.80
    - scipy
    - scikit-learn
    - scikit-learn-intelex
    - pillow
    - xlrd
    - openpyxl==3.1.0
    - defusedxml
    - lxml
    - pyarrow
    - html5lib
    - beautifulsoup4
    - autopep8
    - tabulate
    - mlxtend
